// Encrypts tools/members-source.json into data/members.enc.js
// Usage:  node tools/encrypt-members.mjs "ThePassword"
// The deployed site only ever contains the encrypted output; the plaintext
// source file is excluded from git and Vercel by .gitignore / .vercelignore.

import { readFileSync, writeFileSync } from "fs";
import { webcrypto } from "crypto";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const password = process.argv[2];
if (!password) {
  console.error('Usage: node tools/encrypt-members.mjs "ThePassword"');
  process.exit(1);
}

const ITERATIONS = 310000;
const enc = new TextEncoder();
const data = enc.encode(readFileSync(join(root, "tools", "members-source.json"), "utf8"));

const salt = webcrypto.getRandomValues(new Uint8Array(16));
const iv = webcrypto.getRandomValues(new Uint8Array(12));

const baseKey = await webcrypto.subtle.importKey("raw", enc.encode(password), "PBKDF2", false, ["deriveKey"]);
const key = await webcrypto.subtle.deriveKey(
  { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
  baseKey,
  { name: "AES-GCM", length: 256 },
  false,
  ["encrypt"]
);
const ciphertext = new Uint8Array(await webcrypto.subtle.encrypt({ name: "AES-GCM", iv }, key, data));

const b64 = (u8) => Buffer.from(u8).toString("base64");
const out = `// Generated by tools/encrypt-members.mjs — do not edit by hand.
window.MEMBERS_ENC = ${JSON.stringify({ v: 1, iter: ITERATIONS, salt: b64(salt), iv: b64(iv), data: b64(ciphertext) })};
`;
writeFileSync(join(root, "data", "members.enc.js"), out);
console.log(`Encrypted ${data.length} bytes -> data/members.enc.js (PBKDF2 ${ITERATIONS} iterations, AES-256-GCM)`);
